export const playerNames = {
  0: 'ShadowStriker',
  1: 'NovaBlade',
  2: 'InfernoSpecter',
  3: 'VenomStorm',
  4: 'CyberVortex',
  5: 'RenegadeRaptor',
  6: 'Frostbyte',
  7: 'PhoenixFury',
  8: 'ReaperX',
  9: 'ArcaneNinja',
  10: 'SpectralHaze',
  11: 'GravityGamer',
  12: 'CrimsonBlast',
  13: 'TitanWraith',
  14: 'MysticShadow',
  15: 'ChaosPulse',
  16: 'NeonNinja',
  17: 'IroncladGamer',
  18: 'AstralSkull',
  19: 'BlazeFalcon',
  20: 'Space Invaders',
  21: 'Pac-Man',
  22: 'Pong',
  23: 'Tetris',
  24: 'Super Mario Bros',
  25: 'Donkey Kong',
  26: 'Frogger',
  27: 'Centipede',
  28: 'Galaga',
  29: 'Asteroids',
  30: 'Breakout',
  31: 'Defender',
  32: 'Missile Command',
  33: 'Joust',
  34: 'Q*bert',
  35: 'Dig Dug',
  36: 'Street Fighter II',
  37: 'Mortal Kombat',
  38: 'Mega Man',
  39: 'Castlevania',
  40: 'Duck Hunt',
  41: 'Contra',
  42: 'Spacewar!',
  43: 'Adventure',
  44: 'Pitfall!',
  45: 'Double Dragon',
  46: 'Gauntlet',
  47: 'Bubble Bobble'
}